### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by Strat1987** [fcanas/mirror-displays#11]
On OS X Big Sur 11.6 it seems to be unable to get discovered via Spotlight, nor is the terminal version recognized.

It is in the Applications folder and clicking it does function as expected but this still is quite cumbursome to use.

**Comment by fcanas** [comment]
The first issue seems like a problem with your Spotlight index. If you can double-click on the app, there's no reason it can't be opened via Spotlight.

What does it mean for the terminal version to not be recognized? What does it look like and what behavior are you seeing?

**Comment by Strat1987** [comment]
<img width="620" alt="spotlight" src="https://user-images.githubusercontent.com/3163383/139407303-55c3fc96-24df-42f0-bece-8e0677db0ffb.png">
<img width="235" alt="terminal" src="https://user-images.githubusercontent.com/3163383/139407315-7a556cff-0720-4b50-b876-9c6044d60d44.png">
<img width="600" alt="finder" src="https://user-images.githubusercontent.com/3163383/139407319-e92d46ae-9992-47da-b341-6f23ee04b053.png">

**Comment by fcanas** [comment]
The progress bar and "Indexing..." indicates that macOS isn't finished creating an index of your drive for Spotlight to work properly. Wait until that's finished and it _should_ work. The first Google result for "spotlight not indexing applications" is the Apple help article [Rebuild the Spotlight index on your Mac](https://support.apple.com/en-us/HT201716). I can't help more that that on diagnosing Spotlight issues. I assure you it's nothing to do with MirrorDisplays.

In the command line: I don't have enough information and I don't know how familiar you are with command line tools. It looks like you're running `mirror` from your home directory. Where did you download and unzip the `mirror` binary to? It needs to be somewhere in your shell's path or you need to use a full or relative path. [This article](https://wpbeaches.com/how-to-add-to-the-shell-path-in-macos-using-terminal/) seems to be a friendly introduction to how to think about and worth with your shell's PATH.

**Comment by Strat1987** [comment]
I installed using brew, which is why I expected it on the PATH.

**Comment by fcanas** [comment]
I've never released this via homebrew. I don't know what recipe you used, but if `which mirror` doesn't return anything, it's not on the path.

**Comment by ariofrio** [comment]
The mirror CLI is not included by the ["mirrordisplays" Cask](https://formulae.brew.sh/cask/mirrordisplays), just the GUI app. I opened [a pull request](https://github.com/Homebrew/homebrew-core/pull/89526) to add the `mirror` CLI tool as a separate "mirror" Formula. Thanks for building this great little tool, @fcanas!

**Comment by ariofrio** [comment]
Actually, I just realized that the Mac app has the same source code as the CLI tool, which means /Applications/MirrorDisplays.app/Contents/MacOS/mirror can be used with all the same command line arguments. I added the following to my .zprofile:

```
alias mirror=/Applications/MirrorDisplays.app/Contents/MacOS/mirror
```

**Comment by fcanas** [comment]
I've also recently published my own tap. `brew install fcanas/tap/mirror-displays` should install `mirror` correctly. That tap won't install the "app" version though.
