### ISSUE TITLE
Yosemite compatibility?

### ISSUE THREAD

**Issue by dfbills** [fcanas/mirror-displays#2]
Just found this awesome project and find that it can turn mirroring on in Yosemite, but not off.  Any plans to update?

**Comment by fcanas** [comment]
I've updated the project and build settings. It seems to work fine with two displays in Yosemite for me. If this doesn't work for you, let me know your hardware and setup and I might be able to help.

**Comment by dfbills** [comment]
Here's what I'm seeing:

1. Start in spanned
2. Launch GUI app
3. Screens switch to mirrored mode
4. Gui app quits

All good and console reports:
2/12/15 11:21:50.054 AM WindowServer[139]: Display 0x04248095: GL mask 0x2; bounds (0, 0)[2560 x 1440], 34 modes available
Master in mirror set; Main, Active, on-line, enabled, boot, OpenGL-accel, Vendor 610, Model 9227, S/N 15350956, Unit 1, Rotation 0
UUID 0xa0b594d0d6e4a8c64658b08a8d72f181, ColorSpace { 644068429 }
2/12/15 11:21:50.055 AM WindowServer[139]: Display 0x04248685: GL mask 0x20; bounds (0, 0)[2560 x 1440], 38 modes available
Mirror of 0x4248095; Active, on-line, enabled, OpenGL-accel, Vendor 610, Model 9236, S/N 27b0b00, Unit 5, Rotation 0
UUID 0x88eccb364536859c12a887d96e053ebe, ColorSpace { -123809267 }
2/12/15 11:21:50.594 AM WindowServer[139]: CGXDisplaysDidReconfigure: Displays mirrored

When I try to toggle back, I see:

1. Start in mirrored
2. Launch GUI app
3. Screens dim to black and fail to switch to spawned mode
4. Gui app continues to bounce in the dock for 25-30 secs
5. The console reports:

2/12/15 11:21:56.003 AM WindowServer[139]: CGXDisplaysDidReconfigure: Displays mirrored
2/12/15 11:21:56.034 AM WindowServer[139]: Display 0x04248095: GL mask 0x2; bounds (0, 0)[2560 x 1440], 34 modes available
Master in mirror set; Main, Active, on-line, enabled, boot, OpenGL-accel, Vendor 610, Model 9227, S/N 15350956, Unit 1, Rotation 0
UUID 0xa0b594d0d6e4a8c64658b08a8d72f181, ColorSpace { 644068429 }
2/12/15 11:21:56.034 AM WindowServer[139]: Display 0x04248685: GL mask 0x20; bounds (0, 0)[2560 x 1440], 38 modes available
Mirror of 0x4248095; Active, on-line, enabled, OpenGL-accel, Vendor 610, Model 9236, S/N 27b0b00, Unit 5, Rotation 0
UUID 0x88eccb364536859c12a887d96e053ebe, ColorSpace { -123809267 }

I see very similar behavior with the command-line app.  It even pauses for a good 20-30 seconds after failing to restore the mirrored mode.

Does this help at all?  What else can I provide to help troubleshoot?

Dave

**Comment by fcanas** [comment]
Are you running this with more than two monitors?

**Comment by dfbills** [comment]
I have two monitors attached, but my Mac also sees an AppleTV as a monitor even though I'm not during it.

**Comment by dfbills** [comment]
I've unplugged the AppleTV and am still seeing the same behavior.  I'm running this on a Mac Pro (cylinder) if that helps at all.  10.10.2.

**Comment by fcanas** [comment]
Thanks. I'm going to have to put off looking into it a bit longer. I suspect it might be a Yosemite bug. If I find that's the case, I may need your help filing a Radar.

**Comment by dfbills** [comment]
Sure, just let me know.

**Comment by fcanas** [comment]
@dfbills Any chance any of your displays are rotated? I'm looking into fixing that one since I'm able to reproduce it.

See #3

**Comment by dfbills** [comment]
They’re both in standard orientation.  I haven't looked at this since we last talked in February.

David F. Bills
dfbills@dfbills.com <mailto:dfbills@dfbills.com> | http://dfbills.com <http://dfbills.com/>

**Comment by fcanas** [comment]
I have a fix for a related issue in #5 
It seems that for rotated displays the problem was in whether a mirroring set was hardware or software mirroring set. It seems likely that the underlying fix will also fix your issue. 

Please let me know and thanks for being so patient about this issue.

**Comment by fcanas** [comment]
@dfbills Did you ever get a chance to see whether #5 fixes this issue for you?

**Comment by dfbills** [comment]
I just tested it and it does work with both 2 and 3 monitors.  Thanks!

I tested both the GUI App and Unix executable.

**Comment by fcanas** [comment]
:confetti_ball: 

Thanks so much for finding this issue and helping sort through it. Mirror Displays is much more robust now!

:dancer: :dancers:
