### ISSUE TITLE
10.9.5 Mavericks Mirroring Off Issue

### ISSUE THREAD

**Issue by apizz** [fcanas/mirror-displays#3]
Similar to the Yosemite issue, while I can get mirroring to turn on using the command line commands (-on and -t) I cannot get mirroring to turn off and return to extended display mode (-off or -t)

**Comment by fcanas** [comment]
I wish I could reproduce this so I could work on fixing it. But I can't. Sorry.

**Comment by AnAppAMonth** [comment]
I have the same problem in 10.9.5.
`-on` works, `-off` not. `-q` always shows "off" even after a successful `-on`, maybe that's related? Thanks.

**Comment by AnAppAMonth** [comment]
Upon further experiments it seems that `-off` works when the displays aren't rotated (0 degrees), if they are rotated by 90 degrees it doesn't work.

**Comment by apizz** [comment]
That must have been my problem, as my second display is rotated 90 degrees. Good to know!

**Comment by fcanas** [comment]
@AnAppAMonth Thank you so much. Now that I'm able to reproduce the problem, I'll get to work on it.
