### ISSUE TITLE
Add to homebrew?

### ISSUE THREAD

**Issue by jasonm23** [fcanas/mirror-displays#4]

**Comment by fcanas** [comment]
From home-brew's [Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff) 

> We frown on authors submitting their own work unless it is very popular.

and 

> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.

While this project has been stable for years, and I do plan on maintaining it, I think it might be too obscure for home-brew to want me in particular to submit the formula.

However, I do have a proper [1.0 Release](https://github.com/fcanas/mirror-displays/releases/tag/1.0) that should make it trivially easy for anybody else to submit a formula. Any future changes will also be released.

**Comment by jasonm23** [comment]
Ok.

I will submit it this weekend or sooner.

**Comment by fcanas** [comment]
Thanks. I'm glad you're finding it useful :)

**Comment by jasonm23** [comment]
We run pair programming in our team, so being able to quickly mirror / unmirror seamlessly from the terminal is very helpful

**Comment by fcanas** [comment]
@jasonm23 Any word on whether it's going to make it into homebrew?

**Comment by jasonm23** [comment]
Sorry got sidetracked.  I'll get it done tomorrow (2am here)

**Comment by fcanas** [comment]
Don't worry. I'm in no rush :smile:

**Comment by fcanas** [comment]
@jasonm23 Has there been deny progress on this?

**Comment by jasonm23** [comment]
I'll set it up now.

**Comment by jasonm23** [comment]
https://github.com/Homebrew/homebrew/pull/43079

**Comment by jasonm23** [comment]
Homebrew core says that mirror-displays is not notable enough, and as such considers it a risky proposition to add it, (they'll be the first place people go for support.)

The recommendation is to setup a tap.  I suggest you host this yourself, see below for the docs.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

If you don't have time to do it, I can set it up for you, and then transfer the tap repo to you.

**Comment by fcanas** [comment]
I don't have the time, but I'm also in no hurry. Let me know if there's anything you need form me, like code changes, release tagging, etc.

**Comment by angristan** [comment]
😄 https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mirrordisplays.rb

**Comment by J-M0** [comment]
Hi,

I made a formula file for the command-line portion of this app that doesn't require the full Xcode app to be installed.
If you make a repo for the tap I can make a PR for it.

**Comment by fcanas** [comment]
@J-M0 Sorry for the year+ delay. What are the conventions for a tap repo? With a little more information, I could definitely get that going.

**Comment by ariofrio** [comment]
Oh, sorry I didn't see this before I submitted [the pull request to add `mirror` to homebrew-core](https://github.com/Homebrew/homebrew-core/pull/89526). Looks like they've added mirrordisplays already, so maybe they'd be open to adding the CLI tool now as well? It might also help that you seem intent on maintaining it.

> While this project has been stable for years and I do plan on maintaining it, I think it might be too obscure for home-brew to want _me_ in particular to submit the formula.
> 
> However, I do have a proper [1.0 Release](https://github.com/fcanas/mirror-displays/releases/tag/1.0) that should make it trivially easy for anybody else to submit a formula. Any future changes will also be released.

FWIW, I found this tool because it seems to be the simplest way to functionally "disable" a display on MacOS, according to [this StackOverflow thread](https://superuser.com/a/1642779). (SwitchResX currently can't disable a display on Apple Silicon.)

**Comment by J-M0** [comment]
@fcanas No worries, sorry for my own delay in replying.

Making your own Homebrew tap is pretty simple:

1. Make a repository on GitHub called `homebrew-<tapname>` where `<tapname>` is what you want to name your tap.
2. On your computer run `brew tap-new fcanas/<tapname>` to create a skeleton for your new tap.
3. `cd` to your tap with `cd $(brew --repository fcanas/<tapname>`, add your GitHub repo as a remote named `origin`, and push the files Homebrew committed.

Once you do that I can make a PR to add in the Formula file I made.

**Comment by fcanas** [comment]
I made https://github.com/fcanas/homebrew-tap and added `mirror-displays`

`brew install fcanas/tap/mirror-displays` should install the `mirror` command line tool.
