### ISSUE TITLE
Sierra and El Capitan Compatability

### ISSUE THREAD

**Issue by nmenghardt** [fcanas/mirror-displays#6]
Love the app functionality however it does not seem to work with 10.11 or 10.12. The past behavior of the toggle function not working is back. I am running both 10.11 and 10.12 on separate machines, both with 1 additional display. The app starts mirroring but it will not turn off. Querying the mirroring state while the displays are mirrored shows that mirroring is off. Thanks!

**Comment by kristofferR** [comment]
Weird, works fine for me on 10.12.4.

**Comment by fcanas** [comment]
For both cases, where it's working and not working, knowing your specific machine would help. There's more than one way displays can be mirrored. It's possible virtual mirroring could be affected.

**Comment by kristofferR** [comment]
Eh, I'm on a Hackintosh disguised as an iMac 17,1 with Nvidia 970 GTX.

**Comment by shideg** [comment]
Same symptoms here. 10.12.5, on a 1-year-old iMac.
mirror -on works.
mirror -off does not work.
mirror -q always returns "off".

**Comment by bwbecker** [comment]
I'm seeing the same issue:
* "mirror -on" works
* "mirror -off" does not
* "mirror -q" always reports "off"

Config:  MacBook Pro, 15", 2017 running 10.12.6;  LG 43UD79-B external monitor connected via USB-C.

**Comment by fcanas** [comment]
[Release 1.2](https://github.com/fcanas/mirror-displays/releases/tag/v1.2) has a new linking feature that you might be able to use. You can specify putting a pair of displays into a mirrored set. So if you only have two monitors, `mirror -l 0 1` may be more successful than just `mirror -on`.

I'm curious to know whether this works on your setup. I may add more elaborate query functionality to the program, as the current `-q` functionality was really written with only two displays in mind.

**Comment by nmenghardt** [comment]
I’ll be at our station tomorrow night and can see if it works. We recently got a Mac Pro tower with additional GPU’s to handle the different displays. 

Nick Enghardt

Sent using a mobile device. Please ignore spelling and auto-correct mistakes.

**Comment by fcanas** [comment]
@nmenghardt did it work?

**Comment by fcanas** [comment]
It’s been almost 2 years and I haven’t encountered any situations that can reproduce the issue. Please reach out if this happens again and can help me diagnose what’s happening.
