### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by erkac** [fcanas/mirror-displays#9]
Hey,

is there any chance to distribute binary for the Catalina? I really don't want to install the Xcode just to build this small utility.

Thanks.

**Comment by fcanas** [comment]
Binaries are included with the releases on the [release page](https://github.com/fcanas/mirror-displays/releases).

I believe [mirror.zip](https://github.com/fcanas/mirror-displays/releases/download/v1.2/mirror.zip) contains the command line program, and [MirrorDisplays.zip](https://github.com/fcanas/mirror-displays/releases/download/v1.2/MirrorDisplays.zip) contains the clickable app.

If Catalina kills the executable on startup, you make a security exception in System Preferences:

1. Try to run `mirror` and get the system dialog. The executable exits with `Killed: 9`
2. System Preferences -> Security, there should be a section describing how and why `mirror` could not run, and a button saying "Run anyway"
3. Run `mirror` again. Now you get a different system dialog warning about the security risk. But it now has an "Open" button.

I hope that helps.

**Comment by erkac** [comment]
Works perfectly (now part of my Alfred Workflow)! Sorry I missed the releases page for some reason...
